### ISSUE TITLE
Read Timeout error

### ISSUE THREAD

**Issue by alt44s** [scdl-org/scdl#489]
SCDL was working perfectly until about a week ago, but when I tried downloading an artist's tracks, I got a timeout error. I haven't really changed anything about my setup since it last worked, however it's worth noting that SoundCloud is blocked in Russia, where I am currently located. It's strange that the error is happening now, considering SCDL was working fine until recently.

I'm aware this might be a more isolated issue since I haven't found anything similar in the discussions here, however I would appreciate some pointers as to how I could fix it and if it's something to do with SCDL itself. Thanks.

_Example downloading tracks and reposts from MIMIDEATH:_

![5121](https://github.com/flyingrub/scdl/assets/48489145/8b2c3425-eeae-40d8-a812-3cb4e6c3a572)

_Full log:_

```
PS D:\Downloads\scloud_muse\MIMIDEATH> scdl -l https://soundcloud.com/mimideathh -a
Soundcloud Downloader
Traceback (most recent call last):
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした 。または接続済みのホ ストが応答しなかったため、確立された接続は失敗しました。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='soundcloud.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\Scripts\scdl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 157, in main
    client = SoundCloud(client_id, token if token else None)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\soundcloud\soundcloud.py", line 56, in __init__
    client_id = self.generate_client_id()
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\soundcloud\soundcloud.py", line 197, in generate_client_id
    r = requests.get("https://soundcloud.com")
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\user37\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='soundcloud.com', port=443): Read timed out. (read timeout=None)
```

**Comment by adithayyil** [comment]
Thats weird. Did you try using a VPN perhaps?

**Comment by alt44s** [comment]
Fixed with a vpn/goodbyedpi btw ISP likely blocked it even further.
